In [1]:
import numpy as np

In [28]:
A = np.array([1,2,3,4,5,6,7,8])  #list를 이용해서 numpy배열 생성 
B = np.arange(0,15,2)            #범위를 이용해서 numpy배열 생성 (array range)
C = list(range(1,9,1))

A+B
A+10
B+10
#C+10

print(list(zip(A,B)))
A

[(1, 0), (2, 2), (3, 4), (4, 6), (5, 8), (6, 10), (7, 12), (8, 14)]


array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
for data1, data2 in zip(A,B):
    print(data1, data2)

1 0
2 2
3 4
4 6
5 8
6 10
7 12
8 14


In [41]:
A = np.array([1,2,3,4,5,6,7,8]) 
A[0]
A[-1]
A[0:3]  #0<=  <3
A[:3]   #0<=  <3
A[3:5]  #3<=  <5
A[3:]   #3<=  
A[3:8]   #3<=  <8
A[:]     #0<=  <8
A[0:8:1]
A[0:8:2]
A[::2]
A[-1:-4:-1]  
A[::-1]  
A[-2:]  

array([7, 8])

In [44]:
A = np.array([1,2,3,4,5,6,7,8]) 
A[0]=99
A[0:3] = 88
A

array([88, 88, 88,  4,  5,  6,  7,  8])

In [47]:
A = np.array([1,2,3,4,5,6,7,8]) 
A.size
A[:].size
A[0:3].size

3

In [57]:
alist = [[1,2,3,4,5],[6,7,8,9,10]]
A = np.array(alist)
A.shape
A[1][0]
A[1,0]
A[0].shape
print(A[0])  #1차원 
print(A[:1]) #2차원 
A[0].ndim
A[:1].ndim
A

[1 2 3 4 5]
[[1 2 3 4 5]]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [60]:
alist = [[1,2,3,4,5],[6,7,8,9,10]]
A = np.array(alist)
#값출력

#행벡터를 출력
for data in A:
    print(data)

print(A.shape)
print(A.shape[0])

[1 2 3 4 5]
[ 6  7  8  9 10]
(2, 5)
2


In [62]:
for i in range(A.shape[0]):
    print(A[i])

[1 2 3 4 5]
[ 6  7  8  9 10]


In [63]:
#열벡터 출력 .....행과 열을 교환하는 함수 ....전치행렬(transpose matrix)
A.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [64]:
for data in A.T:
    print(data)

[1 6]
[2 7]
[3 8]
[4 9]
[ 5 10]


In [68]:
#배열의 연산
A = np.array([1,2,3,4])
B = np.array([10,20,30,40])
print("A+B=", A+B)
print("A-B=", A-B)
print("A*B=", A*B)
print("A/B=", A/B)
A = A.reshape(2,2)
B = B.reshape(2,2)
print("A+B=", A+B)
print("A-B=", A-B)
print("A*B=", A*B)
print("A/B=", A/B)

A+B= [11 22 33 44]
A-B= [ -9 -18 -27 -36]
A*B= [ 10  40  90 160]
A/B= [0.1 0.1 0.1 0.1]
A+B= [[11 22]
 [33 44]]
A-B= [[ -9 -18]
 [-27 -36]]
A*B= [[ 10  40]
 [ 90 160]]
A/B= [[0.1 0.1]
 [0.1 0.1]]


In [70]:
A = np.array([[10,20,30,40],[50,60,70,80],[10,20,70,80]])
B = np.array([1,2,3,4])
#B = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])......브로드캐스팅 
print(A.shape)
print(B.shape)
print(A+B)

(3, 4)
(4,)
[[11 22 33 44]
 [51 62 73 84]
 [11 22 73 84]]


In [83]:
A = np.arange(100,2500,100).reshape(2,3,4)
B = np.arange(1,13,1).reshape(3,4)
# [[[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]],
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]]

print(A)
print(B)
print(A+B)
print((A+B).shape, (A+B).ndim)

print(A.size) #전체데이터의 개수 
print(len(A)) #2
print(len(A[0])) #3
print(len(A[0][0])) #4

print(A.shape[0]) #2
print(A.shape[1]) #3
print(A.shape[2]) #4 

[[[ 100  200  300  400]
  [ 500  600  700  800]
  [ 900 1000 1100 1200]]

 [[1300 1400 1500 1600]
  [1700 1800 1900 2000]
  [2100 2200 2300 2400]]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 101  202  303  404]
  [ 505  606  707  808]
  [ 909 1010 1111 1212]]

 [[1301 1402 1503 1604]
  [1705 1806 1907 2008]
  [2109 2210 2311 2412]]]
(2, 3, 4) 3
24
2
3
4
4
2
3
4


In [84]:
A = np.arange(1,21)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [85]:
A % 3 == 0 

array([False, False,  True, False, False,  True, False, False,  True,
       False, False,  True, False, False,  True, False, False,  True,
       False, False])

In [86]:
A[A % 3 == 0 ]

array([ 3,  6,  9, 12, 15, 18])

In [87]:
A[A % 3 == 1 ]

array([ 1,  4,  7, 10, 13, 16, 19])

In [91]:
#3의 나누어 떨어지거나 4로 나눈 나머지가 1인것만 추출 

A[(A%3==0 ) | (A%4==1)]



array([ 1,  3,  5,  6,  9, 12, 13, 15, 17, 18])

In [96]:
A = np.arange(1,10001)
B = np.arange(10001, 20001)
print(A)
print(B)
A+B

[    1     2     3 ...  9998  9999 10000]
[10001 10002 10003 ... 19998 19999 20000]


array([10002, 10004, 10006, ..., 29996, 29998, 30000])

In [97]:
A = np.arange(1,10001)
B = np.arange(1,10001)
A==B

array([ True,  True,  True, ...,  True,  True,  True])

In [107]:
A = np.array([5,23,30,8])
B = np.array([5,6,7,8])
A==B

array([ True, False, False,  True])

In [105]:
np.all(A==B)

False

In [108]:
np.all(A>=B)

True

In [109]:
A>=B

array([ True,  True,  True,  True])

In [116]:
A = np.array([1,2,3,4,5])
np.sum(A)
np.max(A)
np.min(A)
np.std(A)
np.var(A)
np.mean(A)

3.0

In [119]:
A = np.array([[1,2],[3,4]]) 
np.sum(A)
np.sum(A, axis=0)
np.sum(A, axis=1)

array([3, 7])

In [121]:
A = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) 
np.sum(A)
print(np.sum(A, axis=0)) #
print(np.sum(A, axis=1)) #행
print(np.sum(A, axis=2)) #열 


[[ 6  8]
 [10 12]]
[[ 4  6]
 [12 14]]
[[ 3  7]
 [11 15]]


In [125]:
A = np.array([[4,3,5,7],[1,12,11,9],[2,15,1,14]])#3*4

np.sort(A) #열기준sort 
np.sort(A, axis=1) #열기준sort 
np.sort(A, axis=-1) #열기준sort 
np.sort(A, axis=0) #행기준sort 

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [130]:
A = np.array([2,12,5,9])
#자료를 정렬하지는 않고 순서만 알고싶다.
B = np.argsort(A)

#array([0, 2, 3, 1] ==>0번째, 2번째, 3번째, 1번째 
A[B] #np.sort(A)의 결과와 같다.
np.sort(A)
print(B)
#0->2
#2->5
#3->9
#1->12 

[0 2 3 1]


In [149]:
#랜덤 
np.random.seed(100)
A = np.random.rand(5)
np.random.shuffle(A) #NO
print(A)

[0.84477613 0.54340494 0.00471886 0.27836939 0.42451759]


In [155]:
A = np.array([10,30,2,7,5])
np.random.shuffle(A)
print(A)

[10  2  7  5 30]


In [188]:
A = np.array([10,30,2,7,5])

In [202]:
print(np.random.choice(A,7,replace=True))# : data  2arg:갯수(size), ,replace=False (중복하지마라 
print(A)

[ 7  2 30  5  5 30  5]
[10 30  2  7  5]


In [203]:
np.random.choice(10,20) #0<= <10  , 20개 

array([3, 4, 3, 7, 7, 2, 4, 0, 2, 0, 6, 8, 1, 5, 6, 4, 6, 5, 0, 8])

In [180]:
np.random.randint(3,5)  #3<= <5 정수 

4

In [218]:
np.random.randint( 10, size = (3,5)  )

array([[0, 9, 1, 4, 3],
       [1, 0, 6, 9, 9],
       [6, 6, 3, 3, 3]])

In [222]:
A = np.random.randint(10,20, size=(3,5))
print(A)
np.unique(A)

[[17 15 14 10 11]
 [15 19 10 11 10]
 [14 13 12 17 16]]


array([10, 11, 12, 13, 14, 15, 16, 17, 19])

In [223]:
np.unique([10,3,4,5,3,4,5])

array([ 3,  4,  5, 10])

In [224]:
np.unique(["파이썬","자바","파이썬","자바","파이썬","자바","파이썬","자바","파이썬","자바"])

array(['자바', '파이썬'], dtype='<U3')

# Pandas

In [226]:
!pip install pandas

In [225]:
import pandas as pd

In [ ]:
#인덱스없이 Series만들기 (1차원배열과 유사하다. )

In [235]:
s = pd.Series([100,200,300,400,500])
print(s.index)
print(s.values)
s.name = "엔코아"
print(s.name)
s.index.name = "점수"
print(s.index.name)
print(s)
print(s[0]) #index가 0인것의 값 추출 

RangeIndex(start=0, stop=5, step=1)
[100 200 300 400 500]
엔코아
점수
점수
0    100
1    200
2    300
3    400
4    500
Name: 엔코아, dtype: int64
100


In [241]:
s = pd.Series([100,200,300,400,500], index=["서울","대구","부산","광주","인천"])
print(s.index)
print(s.values)
s.name = "엔코아"
print(s.name)
s.index.name = "지역"
print(s.index.name)
print(s)
print(s["서울"]) #index가 "서울"인것의 값 추출 
print(s/10)
print("대구" in s)

Index(['서울', '대구', '부산', '광주', '인천'], dtype='object')
[100 200 300 400 500]
엔코아
지역
지역
서울    100
대구    200
부산    300
광주    400
인천    500
Name: 엔코아, dtype: int64
100
지역
서울    10.0
대구    20.0
부산    30.0
광주    40.0
인천    50.0
Name: 엔코아, dtype: float64
True


In [244]:
#dictionary를 이용해서 Series만들기 key->index 값->값 
s2 = pd.Series({"서울":10, "대구":20, "부산":30, "광주":40,"인천":50 })

print(s2.index)
print(s2.values)
s2.name = "엔코아"
print(s2.name)
s2.index.name = "점수"
print(s2.index.name)
print(s2)
print(s2["서울"]) #index가 "서울"인것의 값 추출 
print(s2/10)
print("대구" in s2)

Index(['서울', '대구', '부산', '광주', '인천'], dtype='object')
[10 20 30 40 50]
엔코아
점수
점수
서울    10
대구    20
부산    30
광주    40
인천    50
Name: 엔코아, dtype: int64
10
점수
서울    1.0
대구    2.0
부산    3.0
광주    4.0
인천    5.0
Name: 엔코아, dtype: float64
True


In [245]:
s - s2

지역
서울     90
대구    180
부산    270
광주    360
인천    450
Name: 엔코아, dtype: int64

In [248]:
#리스트를 이용해서 시리즈만들기 
s = pd.Series([100,200,300,400,500], index=["서울","대구","부산","광주","인천"])
#딕셔너리를 이용해서 시리즈만들기 
s2 = pd.Series({"서울":10, "대전":20, "울산":30, "광주":40,"인천":50 })

#같은 인덱스끼리 연산 
s3 = s - s2

#NaN(Not a Number) 결측값 

In [249]:
#null 이 아닌것 
s3.notnull()

광주     True
대구    False
대전    False
부산    False
서울     True
울산    False
인천     True
dtype: bool

In [250]:
#null 이 아닌것만 추출
s3[s3.notnull()]

광주    360.0
서울     90.0
인천    450.0
dtype: float64

In [251]:
(s-s2)[(s-s2).notnull()]

광주    360.0
서울     90.0
인천    450.0
dtype: float64

In [252]:
#DataFrame 
df = pd.DataFrame({"score":[100,200,300,400,500],
              "eng":["seoul","daegu","inchun","busan","kwangju"],
              "kor":["서울","대구","인천","부산","광주"]
             })
df

score      eng kor
0    100    seoul  서울
1    200    daegu  대구
2    300   inchun  인천
3    400    busan  부산
4    500  kwangju  광주

In [263]:
dict(score=100, eng=200, kor=300) #(score=100, eng=200, kor=300)는 튜플은 아니다. 
#튜플은 값 여러개
a = (1,2,3,4)
type(a)

tuple

In [256]:
s1 = pd.core.series.Series([100,200,300,400,500])
s2 = pd.core.series.Series(["seoul","daegu","inchun","busan","kwangju"])
s3 = pd.core.series.Series(["서울","대구","인천","부산","광주"])
df = pd.DataFrame(data=dict(score=s1, eng=s2, kor=s3)) #"data="부분은 생략가능 
df

score      eng kor
0    100    seoul  서울
1    200    daegu  대구
2    300   inchun  인천
3    400    busan  부산
4    500  kwangju  광주

In [267]:
#list에 list를 넣어서 dataframe만들기 
alist = [[100,"seoul","서울"],[200,"daegu","대구"],[300,"inchun","인천"]]
col_name = ["score","eng","kor"]
df = pd.DataFrame.from_records(alist, columns=col_name)
df

score     eng kor
0    100   seoul  서울
1    200   daegu  대구
2    300  inchun  인천

In [269]:
#dict  ...... dataframe만들기 

adic = {"score":[100,200,300,400,500],
        "kor":["seoul","daegu","inchun","busan","kwangju"],
        "eng":["서울","대구","인천","부산","광주"]
       }
df = pd.DataFrame.from_dict(adic)
df

score      kor eng
0    100    seoul  서울
1    200    daegu  대구
2    300   inchun  인천
3    400    busan  부산
4    500  kwangju  광주

In [277]:
#파일에서 읽어오기 
df = pd.read_csv("frend_list_header.csv")
type(df)  #pandas.core.frame.DataFrame
df

이름  나이  전공
0  왕기  20  컴공
1  아라  30  컴공
2  상수  40  컴공
3  소영  50  컴공
4  서경  60  컴공

In [275]:
%%writefile frend_list_header.csv
이름,나이,전공
왕기,20,컴공
아라,30,컴공
상수,40,컴공
소영,50,컴공
서경,60,컴공

Writing frend_list_header.csv


In [270]:
%%writefile frend_list.csv
왕기,20,컴공
아라,30,컴공
상수,40,컴공
소영,50,컴공
서경,60,컴공

Writing frend_list.csv


In [278]:
#파일에서 읽어오기 
df = pd.read_csv("frend_list.csv", header=None)
type(df)  #pandas.core.frame.DataFrame
df

0   1   2
0  왕기  20  컴공
1  아라  30  컴공
2  상수  40  컴공
3  소영  50  컴공
4  서경  60  컴공

In [283]:
#파일에서 읽어오기 
df = pd.read_("frend_list_header.tsv", "\t") #구분자가 tab임을 명시한다. default=","
type(df)  #pandas.core.frame.DataFrame
df

이름  나이  전공
0  왕기  20  컴공
1  아라  30  컴공
2  상수  40  컴공
3  소영  50  컴공
4  서경  60  컴공

In [287]:
df = pd.read_csv("frend_list.csv", header=None)
df.columns = ["이름", "나이","전공"]
df

이름  나이  전공
0  왕기  20  컴공
1  아라  30  컴공
2  상수  40  컴공
3  소영  50  컴공
4  서경  60  컴공

In [289]:
df.to_csv("frend_list_backup.csv")
df2 = pd.read_csv("frend_list_backup.csv")
df2

Unnamed: 0  이름  나이  전공
0           0  왕기  20  컴공
1           1  아라  30  컴공
2           2  상수  40  컴공
3           3  소영  50  컴공
4           4  서경  60  컴공

In [290]:
df.to_csv("frend_list_backup2.csv", index=False)
df2 = pd.read_csv("frend_list_backup2.csv")
df2

이름  나이  전공
0  왕기  20  컴공
1  아라  30  컴공
2  상수  40  컴공
3  소영  50  컴공
4  서경  60  컴공

In [292]:
df.to_csv("frend_list_backup3.csv", index=False, header=False)
df2 = pd.read_csv("frend_list_backup3.csv", header=None)
df2

0   1   2
0  왕기  20  컴공
1  아라  30  컴공
2  상수  40  컴공
3  소영  50  컴공
4  서경  60  컴공

In [304]:
df = pd.read_csv("frend_list_header.csv")
print(type(df))
print(type(df["이름"]))
print(df["이름"])
print(type(df["나이"]))
print(df["나이"])
print(df.columns)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
0    왕기
1    아라
2    상수
3    소영
4    서경
Name: 이름, dtype: object
<class 'pandas.core.series.Series'>
0    20
1    30
2    40
3    50
4    60
Name: 나이, dtype: int64
Index(['이름', '나이', '전공'], dtype='object')


In [305]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
이름    5 non-null object
나이    5 non-null int64
전공    5 non-null object
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes


In [306]:
%%writefile frend_list_header2.csv
이름,나이,전공
왕기,20,컴공
아라,30,NaN
상수,40,컴공
소영,50,컴공
서경,NaN,컴공

Writing frend_list_header2.csv


In [308]:
df = pd.read_csv("frend_list_header2.csv")
df.to_csv("frend_list_header2_backup.csv", index=False, na_rep="-")

In [309]:
pd.read_csv("frend_list_header2_backup.csv")

이름    나이  전공
0  왕기  20.0  컴공
1  아라  30.0   -
2  상수  40.0  컴공
3  소영  50.0  컴공
4  서경     -  컴공

In [310]:
%%writefile frend_list.csv
왕기,20,컴공
아라,30,NaN
상수,40,컴공
소영,50,컴공
서경,NaN,컴공

Overwriting frend_list.csv


In [317]:
df = pd.read_csv("frend_list.csv")
df.columns = ["a","b","c"]
df

a     b    c
0  아라  30.0  NaN
1  상수  40.0   컴공
2  소영  50.0   컴공
3  서경   NaN   컴공

In [319]:
df = pd.read_csv("frend_list_header.csv")
df

이름  나이  전공
0  왕기  20  컴공
1  아라  30  컴공
2  상수  40  컴공
3  소영  50  컴공
4  서경  60  컴공

In [324]:
df["이름"] #series
df.loc[0, "이름"] #값.....index이름, 칼럼이름 
df.iloc[0, 0]#값 ...행순서,열순서 

'왕기'

In [326]:
df.loc[4, "전공"] #값.....index이름, 칼럼이름 
df.iloc[4, 2]#값 ...행순서,열순서 

'컴공'

In [327]:
df.loc[2]

이름    상수
나이    40
전공    컴공
Name: 2, dtype: object

In [328]:
df.loc[[2,3]]

이름  나이  전공
2  상수  40  컴공
3  소영  50  컴공

In [329]:
#index와 칼럼이름 변경 
df.index = ["a","b","c","d","e"]
df.columns = ["name","age","major"]
df

name  age major
a   왕기   20    컴공
b   아라   30    컴공
c   상수   40    컴공
d   소영   50    컴공
e   서경   60    컴공

In [334]:
#시리즈가져오기 ...칼럼이름이용 
df["age"]

a    20
b    30
c    40
d    50
e    60
Name: age, dtype: int64

In [336]:
type(df.loc["c"]) #Series 
df.loc["c"]

name     상수
age      40
major    컴공
Name: c, dtype: object

In [332]:
df.loc["c","age"]#index, column ==>값 

40

In [338]:
df.loc[['a','c']]

name  age major
a   왕기   20    컴공
c   상수   40    컴공

In [339]:
df.loc[['a','c'],["name","age"]]

name  age
a   왕기   20
c   상수   40

In [343]:
df.iloc[2]
df.iloc[[2,3]]
df.iloc[2,0]
df.iloc[[2,3],[0,1]]

name  age
c   상수   40
d   소영   50

In [348]:
df["name"]
df.loc[:, "name"]

a    왕기
b    아라
c    상수
d    소영
e    서경
Name: name, dtype: object

In [354]:
#조건 ......나이가 >= 30
df["age"]

df[df.age >= 50]

name  age major
d   소영   50    컴공
e   서경   60    컴공

In [359]:
df["age"]
df[df.age >= 50]

name  age major
d   소영   50    컴공
e   서경   60    컴공

In [362]:
df.loc["b","major"] = "국어"
df.loc["c","major"] = "영어"
df

name  age major
a   왕기   20    컴공
b   아라   30    국어
c   상수   40    영어
d   소영   50    컴공
e   서경   60    컴공

In [368]:
df[df.major == "컴공"]

#메서드이용 
df.query('major == "컴공"')
df.query("age>=50")

name  age major
d   소영   50    컴공
e   서경   60    컴공

In [370]:
df.query("(age>=40) & (major=='컴공')")

name  age major
d   소영   50    컴공
e   서경   60    컴공

In [377]:
df[(df.age>=40) & (df.major=='컴공')]

name  age major
d   소영   50    컴공
e   서경   60    컴공

In [395]:
df[["name","age"]] #다중칼럼 추출
df.filter(items=["name","age"])#다중칼럼 추출
df.filter(like='n')  #칼럼의 이름에 문자가 들어간것을 추출 
df.filter(like='n', axis=1)  #칼럼의 이름에 문자가 들어간것을 추출 
df.filter(like='c', axis=0)  #row의 index이름에 'c'문자가 들어간것을 추출 
df.filter(regex='r$', axis=1) #칼럼의 이름이 r로 끝나는 series추출 
df.filter(regex='^a', axis=1)#칼럼의 이름이 a로 시작하는 series추출 


age
a   20
b   30
c   40
d   50
e   60

In [412]:
#index이용 지우기 
#df2 = df.drop(['a','b'])
#df3 = df.drop("age", axis=1)
#df.drop(['a','b'], inplace=True) #지운것을 반영한다.


In [414]:
df.drop("age", axis=1, inplace=True) #지운것을 반영한다.

In [415]:
df

name major
c   상수    영어
d   소영    컴공
e   서경    컴공

In [416]:
df2

name  age major
c   상수   40    영어
d   소영   50    컴공
e   서경   60    컴공

In [435]:
students = [
    { "name":"kim", "midterm":100, "final":90  },
    { "name":"yang", "midterm":90, "final":60  },
    { "name":"park", "midterm":80, "final":70  },
]
df = pd.DataFrame(students, columns=["name","midterm","final"])
df["total"] = df["midterm"] + df["final"]
df["average"] = df["total"] / 2
grades = []

for row in df["average"]:
    if row >=90:
        grades.append("A") 
    elif row>=80:
        grades.append("B") 
    else:
        grades.append("F") 
df["grade"] = grades
df["grade2"] = df.average.apply(f)
df["합격여부"] = df.grade.apply(f2)
df

name  midterm  final  total  average grade grade2 합격여부
0   kim      100     90    190     95.0     A      A   합격
1  yang       90     60    150     75.0     F      F  불합격
2  park       80     70    150     75.0     F      F  불합격

In [433]:
def f2(data):
    if data == 'F':
        return "불합격"
    else:
        return "합격"

In [431]:
def f(data):
    if data>=90:
        return "A"
    elif data>=80:
        return "B"
    else:
        return "F"

In [436]:
df2 = df.copy()
df2

name  midterm  final  total  average grade grade2 합격여부
0   kim      100     90    190     95.0     A      A   합격
1  yang       90     60    150     75.0     F      F  불합격
2  park       80     70    150     75.0     F      F  불합격

In [437]:
df.T

0     1     2
name     kim  yang  park
midterm  100    90    80
final     90    60    70
total    190   150   150
average   95    75    75
grade      A     F     F
grade2     A     F     F
합격여부      합격   불합격   불합격

In [442]:
students = [
    { "name":"kim", "midterm":100, "final":90  },
    { "name":"yang", "midterm":90, "final":60  },
    { "name":"park", "midterm":80, "final":70  },
]
df = pd.DataFrame(students, columns=["name","midterm","final"])

students2 = [
    { "name":"kim2", "midterm":100, "final":90  },
    { "name":"yang2", "midterm":90, "final":60  },
    { "name":"park2", "midterm":80, "final":70  },
]
df2 = pd.DataFrame(students2, columns=["name","midterm","final"])

df3 = df.append(df2, ignore_index=True)
df

name  midterm  final
0   kim      100     90
1  yang       90     60
2  park       80     70

In [446]:
students = [
    { "name":"kim", "midterm":100, "final":90  },
    { "name":"yang", "midterm":90, "final":60  },
    { "name":"park", "midterm":80, "final":70  },
]
df = pd.DataFrame(students, columns=["name","midterm","final"])

students2 = [
    { "name":"kim2", "midterm":100, "final":90  },
    { "name":"yang2", "midterm":90, "final":60  },
    { "name":"park2", "midterm":80, "final":70  },
]
df2 = pd.DataFrame(students2, columns=["name","midterm","final"])
df.append(df2,ignore_index=True)  

name  midterm  final
0    kim      100     90
1   yang       90     60
2   park       80     70
3   kim2      100     90
4  yang2       90     60
5  park2       80     70